### ISSUE TITLE
AssertionError when `b!eval` command is used from bot/cogs/snekbox.py

### ISSUE THREAD

**Issue by AtieP** [AtieP/dpyjs-bot#9]
When using the eval command, but the message from the author contains a blacklisted word, it raises `AssertionError`. We need to fix this immediatly. For now, I will just disable the `snekbox` cog.

**Comment by ghost** [comment]
is there a full stack trace along with the error? where is the assertion made?

**Comment by AtieP** [comment]
I don't know where the assertion is made. And that's the reason I opened this issue. The stack trace:
![Screenshot_2020-10-02_13-46-31](https://user-images.githubusercontent.com/62116490/94920648-fc657a80-04b6-11eb-93d2-f06af2cae40e.png)

**Comment by AtieP** [comment]
This error actually happens when the command is invoked. I will rename the issue title.

**Comment by AtieP** [comment]
Ah, I got the error. I simply put the database URL on the `DPYJS_SNEKBOX_URL` enviroment variable. It's my fault. I am sorry.
